#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\right1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\center1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\down1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\left1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\leftdown1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\leftup1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\rightdown1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\rightup1.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller1\up1.ahk

#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\right2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\center2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\down2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\left2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\leftdown2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\leftup2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\rightdown2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\rightup2.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller2\up2.ahk

#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\right3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\center3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\down3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\left3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\leftdown3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\leftup3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\rightdown3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\rightup3.ahk
#Include %A_ScriptDir%\globalRButton\globalCallers\globalCaller3\up3.ahk
