#Include %A_ScriptDir%\globalRButton\globalLabels\topMost.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\transparency.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\ctrlWinLeftRight.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\restoreMaximizeWindow.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\ctrlAltTab.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\minimizeWindow.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\altTab.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\volume.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\swapMouseButton.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\sendEsc.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\sendEnter.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\runBat.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\shiftWheelUpDown.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\sendCtrlC.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\sendLeftRight.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\sendPgUpDn.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\sendPgUpDn40.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\winKill.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\winTab.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\explorer\copyPath.ahk
