#Include %A_ScriptDir%\globalRButton\globalLabels\topMost.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\transparency.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\ctrlWinLeftRight.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\restoreMaximizeWindow.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\ctrlAltTab.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\minimizeWindow.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\altTab.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\volume.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\swapMouseButton.ahk
#Include %A_ScriptDir%\globalRButton\globalLabels\sendEsc.ahk
